### ISSUE TITLE
mouse duplicate?

### ISSUE THREAD

**Issue by sardukar666** [ngollan/Elite-Binds#1]
Hi, i got no idea how to use this program.

I am looking for a way to map mouse look and mouse ship movement to function at same time.

Any chance you can help. Im looking for solution to help a friend who has to wear a neck brace for awhile.

If toggle head look can the mouse still control the ship pitch up and yaw and turn the headlook in the same direction as ship turns.

Simply want to control ship via headlook mode

**Comment by ngollan** [comment]
Hi, I don't think that's possible. When in mouselook mode, the mouse will only control the viewport.

The game is very much playable without looking around most of the time; my TrackIR is just gathering dust. Your friend should try getting used to flying by the scanner (play with zoom levels) and compass which are both really precise once you wrap your head around them. You could also try mapping a gamepad to taste.

I'm closing this since it's not really an issue with my project, best of luck. If you do manage to get it sorted, I'll be interested to hear how :-)

**Comment by ngollan** [comment]
There are a bunch of options in the bindings file that I can't find in the UI that may be promising:

```
	<MotionHeadlook Value="0" />
	<HeadlookMotionSensitivity Value="1.00000000" />
	<yawRotateHeadlook Value="0" />
```

You could try setting the values of `MotionHeadlook` and `yawRotateHeadlook` to 1 and see if that does anything. You need to exit the game while editing the files.
